### ISSUE TITLE
BUG: Unity5 ecxepitons

### ISSUE THREAD

**Issue by narlee** [FlaShG/GitMerge-for-Unity#51] opened 2015-04-02 22:47 UTC
source exception1:

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.GameObjectTreeViewDataSource.IsUsingAlphaSort () (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/GameObjectTreeViewDataSource.cs:146)
UnityEditor.GameObjectTreeViewDataSource.FetchData () (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/GameObjectTreeViewDataSource.cs:78)
UnityEditor.LazyTreeViewDataSource.GetVisibleRows () (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/LazyTreeViewDataSource.cs:113)
UnityEditor.TreeView.OnGUI (Rect rect, Int32 keyboardControlID) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:404)
UnityEditor.SceneHierarchyWindow.DoTreeView (Single searchPathHeight) (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:347)
UnityEditor.SceneHierarchyWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:195)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

-------------------------------

source exception2:

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.GameObjectTreeViewDataSource.IsUsingAlphaSort () (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/GameObjectTreeViewDataSource.cs:146)
UnityEditor.GameObjectTreeViewDataSource.FetchData () (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/GameObjectTreeViewDataSource.cs:78)
UnityEditor.LazyTreeViewDataSource.GetVisibleRows () (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/LazyTreeViewDataSource.cs:113)
UnityEditor.TreeView.IsVisible (Int32 id) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:819)
UnityEditor.TreeView.RevealNode (Int32 id) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:826)
UnityEditor.TreeView.Frame (Int32 id, Boolean frame, Boolean ping) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:778)
UnityEditor.SceneHierarchyWindow.FrameObjectPrivate (Int32 instanceID, Boolean frame, Boolean ping) (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:724)
UnityEditor.SceneHierarchyWindow.FrameObject (Int32 instanceID, Boolean ping) (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:707)
UnityEditor.EditorGUIUtility.PingObject (Int32 targetInstanceID) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIUtility.gen.cs:461)
UnityEditor.ConsoleWindow.SetActiveEntry (UnityEditorInternal.LogEntry entry) (at C:/buildslave/unity/build/Editor/Mono/ConsoleWindow.cs:300)
UnityEditor.ConsoleWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/ConsoleWindow.cs:455)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by FlaShG** [comment] 2015-04-03 09:55
Duplicate of #17 .

**Closed by FlaShG** 2015-04-03 09:55 UTC
Labels: duplicate
